name: ShinyMusicKit
options:
  bundleIdPrefix: com.shinyorg
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    SKIP_INSTALL: NO
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: NO
    DEFINES_MODULE: YES
    SUPPORTS_MACCATALYST: YES
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  ShinyMusicKit:
    type: framework
    platform: iOS
    sources:
      - path: ShinyMusicKit
        type: group
    settings:
      base:
        INFOPLIST_FILE: ShinyMusicKit/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.shinyorg.shinymusickit
        PRODUCT_NAME: ShinyMusicKit
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - sdk: MusicKit.framework
    scheme:
      gatherCoverageData: false
      shared: true
